trigger:
- master
- release/*

jobs:
- template: jobs/default-build.yml
  parameters:
    jobName: PR_FastCheck
    jobDisplayName: Fast Check
    agentOs: Windows
    buildArgs: "/t:FastCheck"
- template: jobs/default-build.yml
  parameters:
    jobName: Windows_Build
    jobDisplayName: "Build: Windows"
    agentOs: Windows
    beforeBuild:
    - powershell: "& ./src/servers/IIS/tools/UpdateIISExpressCertificate.ps1"
      displayName: Setup IISExpress test certificates
- template: jobs/iisintegration-job.yml
  parameters:
    variables:
      _FolderName: IISIntegration
